"""add_access_requests_and_vault_status

Revision ID: 66e08f54fd96
Revises: 9a1387589973
Create Date: 2026-01-13 14:41:51.131457

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66e08f54fd96'
down_revision: Union[str, None] = '9a1387589973'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create Enums manually for Postgres (Safe if not exists)
    op.execute("""
    DO $$
    BEGIN
        IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'vaultstatus') THEN
            CREATE TYPE vaultstatus AS ENUM ('ACTIVE', 'PENDING');
        END IF;
    END$$;
    """)
    
    op.execute("""
    DO $$
    BEGIN
        IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'accessrequeststatus') THEN
            CREATE TYPE accessrequeststatus AS ENUM ('PENDING', 'APPROVED', 'DENIED', 'EXPIRED');
        END IF;
    END$$;
    """)

    op.execute("""
    CREATE TABLE IF NOT EXISTS access_requests (
        id SERIAL PRIMARY KEY,
        vault_id UUID NOT NULL REFERENCES vaults(id),
        requester_id INTEGER NOT NULL REFERENCES users(id),
        approver_id INTEGER NOT NULL REFERENCES users(id),
        status accessrequeststatus,
        requester_public_key VARCHAR NOT NULL,
        encrypted_share VARCHAR,
        created_at TIMESTAMP,
        expires_at TIMESTAMP NOT NULL
    );
    """)
    
    op.execute("CREATE INDEX IF NOT EXISTS ix_access_requests_id ON access_requests (id);")
    
    op.execute("ALTER TABLE vaults ADD COLUMN IF NOT EXISTS status vaultstatus NOT NULL DEFAULT 'ACTIVE';")
    # Remove default after addition if needed, or keep it.
    op.execute("ALTER TABLE vaults ALTER COLUMN status DROP DEFAULT;")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vaults', 'status')
    op.drop_index(op.f('ix_access_requests_id'), table_name='access_requests')
    op.drop_table('access_requests')
    # ### end Alembic commands ###


