"""add_vault_media_table

Revision ID: 7f4301e37c7f
Revises: 6d5b09365c3b
Create Date: 2025-12-18 13:30:03.726061

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f4301e37c7f'
down_revision: Union[str, None] = '6d5b09365c3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vault_media',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('vault_id', sa.UUID(), nullable=False),
    sa.Column('uploaded_by_id', sa.Integer(), nullable=False),
    sa.Column('media_type', sa.Enum('PHOTO', 'VIDEO', name='mediatype'), nullable=False),
    sa.Column('file_name', sa.String(), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=False),
    sa.Column('storage_key', sa.String(), nullable=False),
    sa.Column('encryption_iv', sa.String(), nullable=False),
    sa.Column('encryption_tag', sa.String(), nullable=False),
    sa.Column('thumbnail_key', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['vault_id'], ['vaults.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('storage_key')
    )
    op.create_index('ix_vault_media_vault_id', 'vault_media', ['vault_id'], unique=False)
    op.create_index('ix_vault_media_uploaded_by_id', 'vault_media', ['uploaded_by_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_vault_media_uploaded_by_id', table_name='vault_media')
    op.drop_index('ix_vault_media_vault_id', table_name='vault_media')
    op.drop_table('vault_media')
    op.execute("DROP TYPE mediatype")
    # ### end Alembic commands ###


