"""add friendship table

Revision ID: e34fc5d85181
Revises: 7f4301e37c7f
Create Date: 2025-12-20 15:08:00.998962

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e34fc5d85181'
down_revision: Union[str, None] = '7f4301e37c7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('friendships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('friend_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['friend_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_friendships_id'), 'friendships', ['id'], unique=False)
    op.drop_index(op.f('ix_vault_media_uploaded_by_id'), table_name='vault_media')
    op.drop_index(op.f('ix_vault_media_vault_id'), table_name='vault_media')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_vault_media_vault_id'), 'vault_media', ['vault_id'], unique=False)
    op.create_index(op.f('ix_vault_media_uploaded_by_id'), 'vault_media', ['uploaded_by_id'], unique=False)
    op.drop_index(op.f('ix_friendships_id'), table_name='friendships')
    op.drop_table('friendships')
    # ### end Alembic commands ###


